#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running Prettier Formatting"
npm run format
echo "Running Lint"
npm run lint
echo "Running tests"
npm run test
echo "Ensure package builds"
npm run package