name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run package
      - run: |
          git config --global user.name "mike-winberry"
          git config --global user.email "cole.winberry@github.com"
          npm version ${{ github.event.release.tag_name }} --allow-same-version
          npm publish -w uui --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
